from __future__ import annotations

STRONG_KEYWORDS: Dict[str, List[str]] = {
    "scraping": [
        "scrape",
        "scraping",
        "extract",
        "extraction",
        "crawler",
        "crawl",
        "parsing",
        "parser",
        "data extraction",
        "web scraping",
        "website scraping",
        "data mining",
        "lead generation",
        "directory scraping",
    ],
    "automation": [
        "automation",
        "bot",
        "workflow",
        "automate",
        "script",
        "browser automation",
        "process automation",
        "task automation",
        "selenium",
        "playwright",
    ],
    "apify": [
        "apify",
        "actor",
        "actors",
        "apify actor",
        "apify store",
        "crawlee",
    ],
    "dashboard": [
        "streamlit",
        "dashboard",
        "analytics dashboard",
        "internal tool",
        "admin panel",
        "reporting dashboard",
        "data dashboard",
        "monitoring dashboard",
    ],
    "data_pipeline": [
        "etl",
        "pipeline",
        "data pipeline",
        "csv",
        "xlsx",
        "json",
        "cleaning",
        "transform",
        "data processing",
        "data validation",
        "data enrichment",
        "normalization",
        "export",
    ],
    "documents": [
        "pdf",
        "report",
        "document generation",
        "invoice",
        "export",
        "reporting",
        "summary report",
        "executive summary",
        "xlsx export",
        "csv export",
    ],
    "python_backend": [
        "python",
        "fastapi",
        "flask",
        "api",
        "rest api",
        "backend",
        "integration",
    ],
    "ai_llm": [
        "openai",
        "gpt",
        "llm",
        "rag",
        "ai assistant",
        "prompt",
        "proposal generator",
        "ai workflow",
    ],
    "trading_prediction": [
        "polymarket",
        "prediction market",
        "prediction markets",
        "market analyzer",
        "trading bot",
        "scalper",
        "market signals",
        "arbitrage",
        "liquidity",
        "clob",
        "gamma api",
        "kalshi",
        "crypto trading",
        "execution engine",
        "trading automation",
        "market data",
        "signal detection",
        "alpha signals",
        "momentum",
        "risk management",
        "order book",
        "market intelligence",
    ],
}

WEAK_SIGNALS = [
    "logo design",
    "figma only",
    "react native",
    "ios app",
    "android app",
    "unity engine",
    "game development",
    "3d modeling",
    "illustration",
    "branding"
]

EXCLUSION_SIGNALS = [
    "commission-only",
    "commission only",
    "cold calling",
    "appointment setting",
    "sales representative",
    "full-time designer",
    "crypto shill",
]

PREMIUM_THRESHOLD = 24
STANDARD_THRESHOLD = 16